bash code/job_submission/submit_job_slurm.sh 1.0 0.0
bash code/job_submission/submit_job_slurm.sh 1.0 -0.5
bash code/job_submission/submit_job_slurm.sh 1.0 -1.0
bash code/job_submission/submit_job_slurm.sh 2.0 0.0
bash code/job_submission/submit_job_slurm.sh 2.0 -0.5
bash code/job_submission/submit_job_slurm.sh 2.0 -2.0
bash code/job_submission/submit_job_slurm.sh 10.0 -0.0
bash code/job_submission/submit_job_slurm.sh 10.0 -5.0
bash code/job_submission/submit_job_slurm.sh 10.0 -10.2
