name: quant-met-computations
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=24.0
  - python=3.12.4
  - datalad=1.1.1
  - jupyterlab=4.2.3
  - pip:
      - click==8.1.7
      - quant-met==0.0.4
      - pre-commit==3.7.1
